# Default values for jupyterhub-ingress-anvil.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
jupyterhub:
  scheduling:
    userScheduler:
      enabled: false
  singleuser:
    cloudMetadata:
      blockWithIptables: false
    profileList:
      - display_name: "Basic Environment"
        description: "A basic environment for quick, and easy tsting. Nothing Special."
        kubespawner_override:
          node_selector:
          # Labels for Node Pools
            env: basic
        default: true
      - display_name: "Datascience Environment"
        description: "Comes with the additional bells and whistles: Python, R, and Julia."
        kubespawner_override:
          image: jupyter/datascience-notebook:2343e33dec46
          node_selector:
          # Labels for Node Pools
            env: datasci
  hub:
    config:
      Authenticator:
        admin_users:
          - user1
          - user2
        allowed_users:
          - user3
          - user4
      DummyAuthenticator:
        password: a-shared-secret-password
      JupyterHub:
        authenticator_class: dummy

ingress:
  enabled: true
  serviceName: proxy-public
  servicePortNumber: 80
  path: /
  pathType: Prefix
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt 

ingress-control:
  ingress-nginx:
    controller:
      service:
        annotations:
          service.beta.kubernetes.io/azure-dns-label-name: "jupyterhub"
          service.beta.kubernetes.io/azure-load-balancer-health-probe-request-path: /healthz
  email: youremail@example.com