# Default values for jupyterhub-ingress-anvil.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

cert-manager:
  installCRDs: true
  nodeSelector:
    kubernetes.io/os: linux
  image:
    repository: quay.io/jetstack/cert-manager-controller
    tag: v1.8.0 
  webhook:
    image:
      repository: quay.io/jetstack/cert-manager-webhook 
      tag: v1.8.0 
  cainjector:
    image:
      repository: quay.io/jetstack/cert-manager-cainjector 
      tag: v1.8.0

ingress-nginx:
  controller:
    service:
      annotations:
        service.beta.kubernetes.io/azure-dns-label-name: "jupyterhub"
        service.beta.kubernetes.io/azure-load-balancer-health-probe-request-path: /healthz

jupyterhub:
  scheduling:
    userScheduler:
      enabled: false
  singleuser:
    cloudMetadata:
      blockWithIptables: false
  hub:
    config:
      Authenticator:
        admin_users:
          - user1
          - user2
        allowed_users:
          - user3
          - user4
      DummyAuthenticator:
        password: a-shared-secret-password
      JupyterHub:
        authenticator_class: dummy

ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
  rules:
    - host: "jupyterhub.southcentralus.cloudapp.azure.com"
      httpPaths:
        - path: /
          pathType: Prefix
          serviceName: proxy-public
          servicePortNumber: 80

email: ooguntol@purdue.edu