kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: data-blob
  annotations:
        volume.beta.kubernetes.io/storage-class: azureblob-nfs-premium
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi