apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-blob
  annotations:
    pv.kubernetes.io/provisioned-by: blob.csi.azure.com
spec:
  capacity:
    storage: 5Gi
  accessModes:
  - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: azureblob-nfs-premium
  csi:
    driver: blob.csi.azure.com
    readOnly: true
    volumeHandle: antidisestablishmentarianism
    volumeAttributes:
      resourceGroup: mc_anvil-reu-tumi_z2jh_southcentralus
      storageAccount: nfsb25feef6aeeb434da9a7
      containerName: dataz
      protocol: nfs
      mountPermissions: "0004"
      fsGroupChangePolicy: Always