kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: data-blob-claim
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 1Gi
  volumeName: data-blob
  storageClassName: azureblob-nfs-premium